dist: xenial
language: minimal
env:
- V=0.26.1
install:
- |
  [ -z "$encrypted_12b15f820731_iv" ] || openssl aes-256-cbc -K $encrypted_12b15f820731_key -iv $encrypted_12b15f820731_iv \
    -in .cache-credentials.json.enc -out .cache-credentials.json -d
- |
  OS=linux
  URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
  wget -O install.sh "${URL}"
  chmod +x install.sh
  ./install.sh --user
  rm -f install.sh
script:
- |
  [ -z "$encrypted_12b15f820731_iv" ] && RC= || RC=--bazelrc=.bazelrc-ci
  bazel $RC build //...
notifications:
  email: false
